export { default as Home } from './Home/Home'
export { default as Register } from './Register/Register'
export { default as Login } from './Login/Login'
export { default as Pricing } from './Pricing/Pricing'
export { default as AboutUs } from './AboutUs/AboutUs'
export { default as MyAppointments } from './MyAppointments/MyAppointments'
export { default as Schedule } from './Schedule/Schedule'
